[old_servers]
old_vm ansible_host=192.168.1.2

[old_servers:vars]
ansible_user=user
ansible_ssh_pass=user
ansible_become_password=user
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[new_servers]
new_vm ansible_host=192.168.1.3

[new_servers:vars]
ansible_user=sdb
ansible_ssh_pass=*sdb2026#
ansible_become_password=*sdb2026#
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
